import { getPost, updatePost, createPostRevision, type PostStatus } from "./posts";
import { getRunWithSteps, updateRun, finalizeWaitingRunsForPost } from "./agent-runs";
import { startRegeneration } from "@/lib/agents/engine";
import { syncPublishedPostToKnowledge } from "@/lib/rag";
import { logAudit } from "./audit";

export type ReviewAction = "approve" | "reject" | "regenerate";

export interface ReviewResult {
  postId: string;
  status: string;
  reviewReason: string | null;
  runId: string | null;
  revisionId?: string;
  newRunId?: string;
  indexing?: { documentId: string; chunks: number; vectors: number } | { error: string };
}

export async function approveArticle(postId: string, actor = "admin"): Promise<ReviewResult> {
  const post = await getPost(postId);
  if (!post) throw new Error("Article not found");

  const rev = await createPostRevision(postId, {
    label: "Approved and published by human editor",
    actor,
    title: post.title,
    excerpt: post.excerpt,
    content: post.content,
  });

  await updatePost(
    postId,
    {
      status: "published" as PostStatus,
      reviewedAt: new Date(),
      reviewedBy: actor,
      reviewReason: null,
    },
    actor
  );

  // Publish -> Knowledge: index the article with the REAL embedding provider so
  // the chatbot retrieves the actual article as a source. Re-read AFTER the
  // status change so the sync always sees the published state and final
  // content. A failure here must be reported, never silently ignored.
  let indexing: ReviewResult["indexing"];
  try {
    const published = await getPost(postId);
    if (!published) throw new Error("Article disappeared during publish");
    indexing = await syncPublishedPostToKnowledge(published, `publish-${postId}`);
  } catch (err) {
    indexing = { error: err instanceof Error ? err.message : String(err) };
  }

  // Run state consistency: a post may own MULTIPLE runs (regenerations).
  // Finalize every waiting_for_human run linked to this post, not just the
  // currently-linked one, so Admin → Agent Runs can never show stale
  // "waiting for human" rows for a published article.
  const finalizedRunIds = await finalizeWaitingRunsForPost(postId);
  const run = post.agentRunId ? await getRunWithSteps(post.agentRunId) : null;

  await logAudit({
    actor,
    action: "review.approved",
    target: postId,
    metadata: {
      ...(indexing && "error" in indexing ? { indexingError: indexing.error } : {}),
      ...(finalizedRunIds.length ? { finalizedRunIds } : {}),
    },
  });

  return { postId, status: "published", reviewReason: null, runId: run?.id ?? null, revisionId: rev.id, indexing };
}

export async function rejectArticle(postId: string, reason: string, actor = "admin"): Promise<ReviewResult> {
  const post = await getPost(postId);
  if (!post) throw new Error("Article not found");

  const rev = await createPostRevision(postId, {
    label: "Rejected by human editor",
    actor,
    title: post.title,
    excerpt: post.excerpt,
    content: post.content,
    reason,
  });

  await updatePost(
    postId,
    {
      status: "rejected" as PostStatus,
      reviewedAt: new Date(),
      reviewedBy: actor,
      reviewReason: reason,
    },
    actor
  );

  // Rejection also terminates the human decision: no run linked to this post
  // may remain waiting_for_human afterwards.
  await finalizeWaitingRunsForPost(postId);

  const logAuditMeta = { actor, action: "review.rejected", target: postId, metadata: { reason } };
  await logAudit(logAuditMeta);

  return { postId, status: "rejected", reviewReason: reason, runId: post.agentRunId ?? null, revisionId: rev.id };
}

export async function regenerateArticle(
  postId: string,
  input: { language?: "en" | "fa"; categoryId?: string | null } = {},
  actor = "admin"
): Promise<ReviewResult> {
  const post = await getPost(postId);
  if (!post) throw new Error("Article not found");

  const { runId } = await startRegeneration({
    topic: post.title,
    language: input.language ?? (post.language as "en" | "fa") ?? "en",
    categoryId: input.categoryId ?? post.categoryId,
    postId,
  });

  const rev = await createPostRevision(postId, {
    label: "Regenerated by human editor — new agent run started",
    actor,
    title: post.title,
  });

  // Reset the post to a draft so it is clearly not published while regenerating.
  await updatePost(
    postId,
    {
      status: "draft" as PostStatus,
      reviewedAt: new Date(),
      reviewedBy: actor,
      reviewReason: null,
    },
    actor
  );

  await logAudit({ actor, action: "review.regenerated", target: postId, metadata: { runId } });

  // The new run is linked to this post, so the engine will overwrite it when it completes.
  return { postId, status: "draft", reviewReason: null, runId, revisionId: rev.id, newRunId: runId };
}